-- 0013 · anthropic_calls
--
-- Self-tracked ledger of every Anthropic API call the app makes. The
-- Anthropic Admin API exposes cost_report and usage_report but both
-- have multi-hour-to-day ingestion lag (verified 2026-05-22 · console
-- showed $0.14 spent while the API returned only $0.0032 / 16 tokens
-- for the same period). The console's live "spent" figure has no
-- public Admin API equivalent.
--
-- Solution: log every messages.create() call ourselves. This gives
-- the admin dashboard a true running total of Counsel.day-product
-- spend. It does NOT include external usage on the same API key
-- (Claude Code, ad-hoc scripts) · that's by design, since this table
-- is scoped to the product.
--
-- Inserts go through src/lib/anthropic-call.ts which wraps the SDK
-- so no caller can forget to log.

BEGIN;

CREATE TABLE IF NOT EXISTS anthropic_calls (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  called_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Where the call originated. Free-text so we can add new sources
  -- (chatbot, time_capsule, etc.) without a migration. Convention:
  --   'verdict_cron'   · src/jobs/cron.ts verdictGenerate
  --   'testing_area'   · /admin/testing-area/run-verdict
  --   'chatbot'        · future helper bot
  source          TEXT NOT NULL,
  model           TEXT NOT NULL,
  -- Token + cost columns mirror the existing verdicts.tokens_* /
  -- cost_cents shape so an UNION view across tables is easy if
  -- finance ever wants one. cost_cents is computed via
  -- lib/anthropic-pricing.ts calculateAnthropicCostCents() · same
  -- source of truth as the verdicts table.
  tokens_input    INTEGER NOT NULL DEFAULT 0,
  tokens_output   INTEGER NOT NULL DEFAULT 0,
  cost_cents      INTEGER NOT NULL DEFAULT 0,
  -- Optional back-pointers so the admin can drill from a call row
  -- into the verdict / test_run that triggered it. NULL is fine for
  -- sources that don't have a corresponding row (chatbot, etc.).
  decision_id     UUID REFERENCES decisions(id) ON DELETE SET NULL,
  test_run_id     UUID REFERENCES verdict_test_runs(id) ON DELETE SET NULL,
  -- Anthropic's response request_id (req_011C...) · lets the operator
  -- look up a specific call in Anthropic's own audit trail.
  request_id      TEXT,
  duration_ms     INTEGER NOT NULL DEFAULT 0,
  ok              BOOLEAN NOT NULL DEFAULT TRUE,
  error           TEXT
);

-- Hot path: admin overview pulls SUM + last call by recency. The
-- partial index on ok=true keeps successful-call totals fast even
-- if the failure table grows.
CREATE INDEX IF NOT EXISTS anthropic_calls_called_at_idx
  ON anthropic_calls (called_at DESC);

CREATE INDEX IF NOT EXISTS anthropic_calls_source_idx
  ON anthropic_calls (source);

CREATE INDEX IF NOT EXISTS anthropic_calls_ok_called_at_idx
  ON anthropic_calls (called_at DESC) WHERE ok = TRUE;

COMMIT;
