-- 0014 · chatbot_queries
--
-- Captures every user → bot turn so the operator can read real queries
-- and tune the knowledge base. Independent of anthropic_calls (which
-- stores cost / token metadata for ALL Anthropic invocations) · this
-- table stores the actual prompt + reply text for chatbot turns only.
--
-- Retention: 90 days. The audit-prune cron deletes rows older than
-- that (see src/jobs/cron.ts auditPrune). Anonymised export is fine;
-- the table holds PII (the user's exact wording) and must NOT be
-- shared outside the operator's admin view.

BEGIN;

CREATE TABLE IF NOT EXISTS chatbot_queries (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asked_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  user_id         UUID REFERENCES users(id) ON DELETE SET NULL,
  question        TEXT NOT NULL,
  reply           TEXT NOT NULL,
  escalated       BOOLEAN NOT NULL DEFAULT FALSE,
  tokens_input    INTEGER NOT NULL DEFAULT 0,
  tokens_output   INTEGER NOT NULL DEFAULT 0,
  duration_ms     INTEGER NOT NULL DEFAULT 0,
  -- Anthropic_calls.id of the call that produced this reply · lets
  -- the operator pivot between the cost-tracking view and the
  -- content view for the same call.
  anthropic_call_id INTEGER REFERENCES anthropic_calls(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS chatbot_queries_asked_at_idx
  ON chatbot_queries (asked_at DESC);

CREATE INDEX IF NOT EXISTS chatbot_queries_user_id_idx
  ON chatbot_queries (user_id);

CREATE INDEX IF NOT EXISTS chatbot_queries_escalated_idx
  ON chatbot_queries (asked_at DESC) WHERE escalated = TRUE;

COMMIT;
