-- 0015 · verdict_shares
--
-- Tokenised public share links for premium verdicts. The owner of a
-- decision generates a long random token via POST /api/verdict-report/
-- share. The recipient opens /share.html?token=<token> in a browser
-- with no Counsel.day account · they see the prose verdict, the
-- question, the partner first-names, and the verdict-day date. They
-- do NOT see vote notes, conviction sliders, the sentiment or
-- vocabulary analysis, the cron status, or the owner's email.
--
-- Tokens are revocable (set revoked_at) and expirable (set expires_at,
-- nullable for "no expiry"). The public-fetch route checks both.

BEGIN;

CREATE TABLE IF NOT EXISTS verdict_shares (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  decision_id     UUID NOT NULL REFERENCES decisions(id) ON DELETE CASCADE,
  owner_user_id   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- Long random URL-safe token · 32 chars from a base64url alphabet
  -- gives ~190 bits of entropy. Enforced unique so a leaked token
  -- can't be used to brute-force others.
  token           TEXT NOT NULL,
  -- What the recipient is allowed to see. Defaults: prose + question
  -- + partner names + verdict-day date. Notes and votes are NEVER
  -- shareable; the recipient is not entitled to that level of
  -- intimacy regardless of the owner's preference.
  allow_partner_names BOOLEAN NOT NULL DEFAULT TRUE,
  allow_analysis      BOOLEAN NOT NULL DEFAULT FALSE,
  -- Lifecycle timestamps · created_at always set; revoked_at set
  -- when the owner clicks Revoke; expires_at optional (NULL = never).
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  revoked_at      TIMESTAMPTZ,
  expires_at      TIMESTAMPTZ,
  -- Counter so the owner can see how often the link has been opened.
  -- Incremented atomically on every successful public fetch.
  view_count      INTEGER NOT NULL DEFAULT 0,
  last_viewed_at  TIMESTAMPTZ
);

-- Lookups are by token (public fetch) and by (owner, decision) so
-- the owner can list their existing share links from the report page.
CREATE UNIQUE INDEX IF NOT EXISTS verdict_shares_token_uniq
  ON verdict_shares (token);

CREATE INDEX IF NOT EXISTS verdict_shares_decision_owner_idx
  ON verdict_shares (decision_id, owner_user_id);

-- Hot path: public fetch should only ever see active (not revoked,
-- not expired) shares. Partial index keeps that scan O(1).
CREATE INDEX IF NOT EXISTS verdict_shares_active_idx
  ON verdict_shares (token)
  WHERE revoked_at IS NULL;

COMMIT;
