-- 0016 · prompts
--
-- Versioned storage for AI system prompts. Today the verdict synthesis
-- prompt + chatbot system prompt live as TypeScript constants in
-- lib/anthropic.ts and lib/chatbot-knowledge.ts respectively. Every
-- copy edit requires a code redeploy.
--
-- This table lets the operator edit prompts via /admin-prompt-editor
-- and have the change take effect on the next request (5-min cache).
-- Versioning is built-in · every save creates a new row with version+1,
-- the previously-active row's is_active flips to false, and the new
-- row's is_active is true. Activate any prior version with one click
-- to roll back.
--
-- At runtime, lib/prompts.ts reads the active row for a given kind,
-- falling back to the in-code constant when no DB row exists for that
-- kind (clean boot · production starts on the code-baked prompts then
-- accepts overrides as they're saved).

BEGIN;

CREATE TABLE IF NOT EXISTS prompts (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Free-text key · current values: 'verdict_synthesis', 'chatbot_system'.
  -- New kinds can be added without a migration (just save a first row).
  kind            TEXT NOT NULL,
  -- Auto-incremented within a kind on every save (handled application-side
  -- · we take MAX(version)+1 in the same transaction as the insert).
  version         INTEGER NOT NULL,
  -- The actual system prompt text. No length cap · Postgres TEXT scales.
  text            TEXT NOT NULL,
  -- Optional changelog note: "tightened the no-em-dash rule" etc.
  notes           TEXT,
  -- Who saved this version, for audit. Nullable when set via tsx
  -- without a session (e.g. migrations or scripts).
  created_by      UUID REFERENCES users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  -- Exactly one row per kind has is_active = true at any time. Enforced
  -- by the partial unique index below.
  is_active       BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX IF NOT EXISTS prompts_active_per_kind
  ON prompts (kind) WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS prompts_kind_version_idx
  ON prompts (kind, version DESC);

COMMIT;
