"""
csp-hash-allowlist.py · generate the SHA-256 allowlist for the
CSP hash-based migration described in docs/CSP_NONCE_MIGRATION.md.

Writes two artefacts:
  · partials/csp-hashes.txt     · single-line space-separated 'sha256-...'
                                   entries, ready to splice into the
                                   Caddyfile via env-var substitution.
  · partials/csp-hashes.json    · structured form { script: [...],
                                   style: [...] } for review and tooling.

Usage:
  python scripts/csp-hash-allowlist.py            # regenerate the files
  python scripts/csp-hash-allowlist.py --check    # exit 1 if regenerating
                                                  # would change the artefacts
                                                  # (suitable for pre-commit
                                                  # and brand-verify).

Caddyfile integration (NOT yet active · flip when ready):

  After running this script you have the file partials/csp-hashes.txt.
  The Caddyfile reads it via {file.partials/csp-hashes.txt} or you can
  load it into env via the systemd ExecStartPre. Replace 'unsafe-inline'
  in the existing CSP with the contents of this file. Test in staging
  before production · one missing hash silently breaks the page.

Re-run any time an inline <script> or <style> block changes. Brand-verify
gate (Check 16 in scripts/brand-verify.ps1) will fail the build if the
artefacts are stale.
"""

from __future__ import annotations
import base64
import hashlib
import json
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
OUT_DIR = os.path.join(ROOT, 'partials')
TXT_PATH = os.path.join(OUT_DIR, 'csp-hashes.txt')
JSON_PATH = os.path.join(OUT_DIR, 'csp-hashes.json')

EXCLUDE_DIRS = {'scripts', 'ops', 'partials', 'fonts', 'icons', 'photos'}

INLINE_SCRIPT = re.compile(r'<script(?![^>]*\bsrc=)[^>]*>(.*?)</script>', re.DOTALL)
INLINE_STYLE = re.compile(r'<style[^>]*>(.*?)</style>', re.DOTALL)


def sha256_b64(body: str) -> str:
    digest = hashlib.sha256(body.encode('utf-8')).digest()
    return base64.b64encode(digest).decode('ascii')


def walk():
    for dirpath, dirnames, filenames in os.walk(ROOT):
        rel = os.path.relpath(dirpath, ROOT)
        parts = set(rel.split(os.sep)) if rel != '.' else set()
        if parts & EXCLUDE_DIRS:
            dirnames[:] = []
            continue
        for fn in filenames:
            if fn.endswith('.html'):
                yield os.path.join(dirpath, fn)


def collect() -> tuple[list[str], list[str]]:
    script_hashes: set[str] = set()
    style_hashes: set[str] = set()
    for path in walk():
        with open(path, 'r', encoding='utf-8') as fh:
            text = fh.read()
        for body in INLINE_SCRIPT.findall(text):
            script_hashes.add(sha256_b64(body))
        for body in INLINE_STYLE.findall(text):
            style_hashes.add(sha256_b64(body))
    return sorted(script_hashes), sorted(style_hashes)


def render_outputs(script: list[str], style: list[str]) -> tuple[str, str]:
    quoted_scripts = ' '.join(f"'sha256-{h}'" for h in script)
    quoted_styles = ' '.join(f"'sha256-{h}'" for h in style)
    txt = (
        '# Counsel.day CSP hash allowlist · regenerated by '
        'scripts/csp-hash-allowlist.py\n'
        '# script-src adjunct (paste after `script-src ...`):\n'
        f'{quoted_scripts}\n\n'
        '# style-src adjunct (paste after `style-src ...`):\n'
        f'{quoted_styles}\n'
    )
    js = json.dumps({'script': script, 'style': style}, indent=2)
    return txt, js


def main() -> int:
    check_mode = '--check' in sys.argv
    os.makedirs(OUT_DIR, exist_ok=True)
    script, style = collect()
    txt, js = render_outputs(script, style)

    existing_txt = open(TXT_PATH, encoding='utf-8').read() if os.path.exists(TXT_PATH) else ''
    existing_js = open(JSON_PATH, encoding='utf-8').read() if os.path.exists(JSON_PATH) else ''

    drift = (existing_txt != txt) or (existing_js != js)

    if check_mode:
        if drift:
            print('CSP hash allowlist is STALE. Run scripts/csp-hash-allowlist.py and commit.')
            return 1
        print(f'CSP hash allowlist is in sync · {len(script)} script + {len(style)} style entries.')
        return 0

    with open(TXT_PATH, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(txt)
    with open(JSON_PATH, 'w', encoding='utf-8', newline='\n') as fh:
        fh.write(js)
    print(f'Wrote {len(script)} script hash(es) + {len(style)} style hash(es)')
    print(f'  · {os.path.relpath(TXT_PATH, ROOT)}')
    print(f'  · {os.path.relpath(JSON_PATH, ROOT)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
