#!/usr/bin/env bash
# ============================================================
# COUNSEL.DAY · SITEMAP REGENERATOR
# Crawls /var/www/counsel.day/ for *.html files, filters out
# noindex / app-surface / admin pages per the same exclusion
# list as the brand-verify script, and writes a fresh
# sitemap.xml at the site root.
#
# Triggered by:
#   - systemd timer counsel-day-sitemap.timer (weekly, Sundays 04:00 UTC)
#   - manual:  sudo systemctl start counsel-day-sitemap.service
#
# Why a shell script and not a Next.js endpoint: the sitemap regen
# only touches static files on disk. Pulling Next.js into the loop
# adds a deploy-and-restart dependency for something that's
# fundamentally `find + xargs`.
# ============================================================
set -euo pipefail

SITE_ROOT="${SITE_ROOT:-/var/www/counsel.day}"
SITE_HOST="${SITE_HOST:-https://counsel.day}"
OUT="$SITE_ROOT/sitemap.xml"
LAST_MOD=$(date -u +%Y-%m-%d)

if [ ! -d "$SITE_ROOT" ]; then
  echo "[sitemap · ERROR] $SITE_ROOT does not exist." >&2
  exit 1
fi

echo "[sitemap · start] $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "[sitemap · root]  $SITE_ROOT"
echo "[sitemap · host]  $SITE_HOST"

# Pages to exclude · mirror the robots.txt Disallow + admin carve-out.
# Any file matching one of these (basename or relative path prefix)
# is skipped.
EXCLUDE=(
  # Auth-gated / private app surface
  "account.html" "billing.html" "decisions.html" "decision.html"
  "compose.html" "vote-today.html" "verdict-reveal.html" "invite.html"
  # Admin
  "admin.html"
  # Auth-edge transient pages
  "verify-email.html" "signed-out.html" "session-expired.html"
  "forgot-password.html" "reset-password.html"
  # System / error pages
  "404.html" "500.html" "maintenance.html" "offline.html"
  # Internal-only
  "homepage.html" "components.html" "og-image-generator.html"
)

is_excluded() {
  local name="$1"
  for ex in "${EXCLUDE[@]}"; do
    [ "$name" = "$ex" ] && return 0
  done
  return 1
}

# Find every .html file under the site root, sort for stable output
mapfile -t ALL_HTML < <(cd "$SITE_ROOT" && find . -type f -name '*.html' -not -path './engineering/*' | sed 's|^\./||' | sort)

# Build URL list
URLS=()
SKIPPED=0
for f in "${ALL_HTML[@]}"; do
  base=$(basename "$f")
  if is_excluded "$base"; then
    SKIPPED=$((SKIPPED + 1))
    continue
  fi
  # Strip .html for the canonical URL on root-level pages, keep paths
  # for subdirectories. index.html → / (root).
  if [ "$f" = "index.html" ]; then
    URLS+=("$SITE_HOST/")
  elif [[ "$f" == */index.html ]]; then
    URLS+=("$SITE_HOST/${f%/index.html}/")
  else
    URLS+=("$SITE_HOST/$f")
  fi
done

echo "[sitemap · scan] ${#URLS[@]} pages included, $SKIPPED excluded"

# Write the sitemap. The XML is intentionally simple · no <priority>
# (Google ignores it), no <changefreq> (Google ignores it), just <loc>
# and <lastmod> per https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap
{
  echo '<?xml version="1.0" encoding="UTF-8"?>'
  echo '<!-- Generated by scripts/regenerate-sitemap.sh -->'
  echo "<!-- Last generated: $(date -u +%Y-%m-%dT%H:%M:%SZ) -->"
  echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
  for u in "${URLS[@]}"; do
    echo "  <url>"
    echo "    <loc>$u</loc>"
    echo "    <lastmod>$LAST_MOD</lastmod>"
    echo "  </url>"
  done
  echo '</urlset>'
} > "$OUT"

SIZE=$(stat -c%s "$OUT")
echo "[sitemap · wrote] $OUT (${SIZE} bytes, ${#URLS[@]} URLs)"
echo "[sitemap · done]  $(date -u +%Y-%m-%dT%H:%M:%SZ)"
